name: datetime_difference
description: Calculates the difference between two dates. It returns a string with the difference in years, months, days, hours, minutes and seconds.
version: 1.0.4
homepage: https://github.com/gabrielkipper1/
repository: https://github.com/gabrielkipper1/datetime_difference
issue_tracker: https://github.com/gabrielkipper1/datetime_difference/issues

environment:
  sdk: '>=2.18.1 <=3.19.2'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
